-- =============================================================================
-- Supabase data_config 테이블 및 RLS 설정
-- (열 설정 모달에서 프리셋 선택 시 오른쪽 열 목록이 갱신되도록)
-- Supabase Dashboard > SQL Editor 에서 실행하세요.
-- =============================================================================

-- 1) 테이블이 없다면 생성 (이미 있으면 건너뛰기)
CREATE TABLE IF NOT EXISTS public.data_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key TEXT NOT NULL,
    layout_name TEXT,
    columns_layout JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2) columns_layout 이 TEXT 로 되어 있으면 JSONB 로 변경 (한 번만 실행)
--    Supabase 대시보드에서 columns_layout 타입 확인 후, TEXT 이면 아래 한 줄 실행:
--    ALTER TABLE public.data_config ALTER COLUMN columns_layout TYPE JSONB USING columns_layout::jsonb;
--    이미 JSONB 이면 실행하지 마세요.

-- 3) 인덱스 (프로젝트별 조회용)
CREATE INDEX IF NOT EXISTS idx_data_config_project_key ON public.data_config(project_key);
CREATE INDEX IF NOT EXISTS idx_data_config_created_at ON public.data_config(created_at);

-- 4) RLS 활성화
ALTER TABLE public.data_config ENABLE ROW LEVEL SECURITY;

-- 5) [필수] RLS 정책 추가
--    4번만 실행하고 5번을 실행하지 않으면 정책이 없어서 모든 접근이 차단됩니다.
--    (SELECT가 실패해 열 설정 모달 오른쪽 목록이 비거나 갱신되지 않을 수 있음)
--    아래 블록을 Supabase SQL Editor에서 실행하세요.
DROP POLICY IF EXISTS "data_config_select" ON public.data_config;
CREATE POLICY "data_config_select" ON public.data_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "data_config_insert" ON public.data_config;
CREATE POLICY "data_config_insert" ON public.data_config FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "data_config_update" ON public.data_config;
CREATE POLICY "data_config_update" ON public.data_config FOR UPDATE USING (true);

DROP POLICY IF EXISTS "data_config_delete" ON public.data_config;
CREATE POLICY "data_config_delete" ON public.data_config FOR DELETE USING (true);

-- 6) columns_layout 구조 참고 (id, defaultName, customName, isVisible, width, fixed 등)
--    fixed 는 선택이며, width 없으면 프론트에서 150 적용.
--
-- [5번만 실행하기] 이미 4번까지 실행했고 정책만 추가하려면: 위의 "5) [필수] RLS 정책 추가" 블록만
-- 복사해서 Supabase SQL Editor에 붙여 넣고 실행하면 됩니다.

-- 7) [선택] "마지막으로 저장한" 프리셋을 테이블 헤더에 쓰려면 updated_at 추가
--    아래 실행 시 페이지 로드 시 updated_at 기준 최신 1건을 사용합니다.
/*
ALTER TABLE public.data_config ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS data_config_updated_at ON public.data_config;
CREATE TRIGGER data_config_updated_at BEFORE UPDATE ON public.data_config FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
*/

-- [참고] 열 설정을 건드린 적이 없을 때
-- data_config 에 해당 project_key 행이 없으면, 프론트에서 기본 레이아웃을 씁니다.
-- 이때 헤더는 "필드 1" ~ "필드 6"(처음 6개만 보임), "필드 7" ~ "필드 20"(숨김) 이 됩니다.
